name: CICD

on:
  push:
    branches: [cicd-docker-ec2]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} 
      - name: Build docker image
        run: docker build -t integrationninjas/my-first-strapi-project .
      - name: Publish image to docker hub
        run: docker push integrationninjas/my-first-strapi-project:latest
  
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: docker pull integrationninjas/my-first-strapi-project:latest
      - name: Delete old container
        run: docker rm -f my-first-strapi-project-container
      - name: Run docker container
        run: docker run -d -p 1337:1337 --name my-first-strapi-project-container integrationninjas/my-first-strapi-project
